// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: chunk.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteChunkRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ChunkHandle *ChunkHandle           `protobuf:"bytes,1,opt,name=chunk_handle,json=chunkHandle,proto3" json:"chunk_handle,omitempty"`
	// Byte offset within the chunk
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Data to write
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteChunkRequest) Reset() {
	*x = WriteChunkRequest{}
	mi := &file_chunk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteChunkRequest) ProtoMessage() {}

func (x *WriteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteChunkRequest.ProtoReflect.Descriptor instead.
func (*WriteChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{0}
}

func (x *WriteChunkRequest) GetChunkHandle() *ChunkHandle {
	if x != nil {
		return x.ChunkHandle
	}
	return nil
}

func (x *WriteChunkRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteChunkResponse) Reset() {
	*x = WriteChunkResponse{}
	mi := &file_chunk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteChunkResponse) ProtoMessage() {}

func (x *WriteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteChunkResponse.ProtoReflect.Descriptor instead.
func (*WriteChunkResponse) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{1}
}

func (x *WriteChunkResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type ReadChunkRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ChunkHandle *ChunkHandle           `protobuf:"bytes,1,opt,name=chunk_handle,json=chunkHandle,proto3" json:"chunk_handle,omitempty"`
	// Starting byte
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Number of bytes to read
	Length        uint64 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunkRequest) Reset() {
	*x = ReadChunkRequest{}
	mi := &file_chunk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunkRequest) ProtoMessage() {}

func (x *ReadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunkRequest.ProtoReflect.Descriptor instead.
func (*ReadChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{2}
}

func (x *ReadChunkRequest) GetChunkHandle() *ChunkHandle {
	if x != nil {
		return x.ChunkHandle
	}
	return nil
}

func (x *ReadChunkRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadChunkRequest) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ReadChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunkResponse) Reset() {
	*x = ReadChunkResponse{}
	mi := &file_chunk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunkResponse) ProtoMessage() {}

func (x *ReadChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunkResponse.ProtoReflect.Descriptor instead.
func (*ReadChunkResponse) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{3}
}

func (x *ReadChunkResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ReadChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHandle   *ChunkHandle           `protobuf:"bytes,1,opt,name=chunk_handle,json=chunkHandle,proto3" json:"chunk_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkRequest) Reset() {
	*x = DeleteChunkRequest{}
	mi := &file_chunk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkRequest) ProtoMessage() {}

func (x *DeleteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkRequest.ProtoReflect.Descriptor instead.
func (*DeleteChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteChunkRequest) GetChunkHandle() *ChunkHandle {
	if x != nil {
		return x.ChunkHandle
	}
	return nil
}

type DeleteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkResponse) Reset() {
	*x = DeleteChunkResponse{}
	mi := &file_chunk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkResponse) ProtoMessage() {}

func (x *DeleteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkResponse.ProtoReflect.Descriptor instead.
func (*DeleteChunkResponse) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteChunkResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which chunk server is sending this heartbeat
	Server *ServerInfo `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// Chunks currently stored on this server
	Chunks []*ChunkHandle `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	// Remaining free disk space (bytes)
	AvailableSpace uint64 `protobuf:"varint,3,opt,name=available_space,json=availableSpace,proto3" json:"available_space,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_chunk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetServer() *ServerInfo {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *HeartbeatRequest) GetChunks() []*ChunkHandle {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *HeartbeatRequest) GetAvailableSpace() uint64 {
	if x != nil {
		return x.AvailableSpace
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_chunk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type RangeDeleteChunkRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Path             string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset           uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length           uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	BeforeRange      []*ChunkLocation       `protobuf:"bytes,4,rep,name=before_range,json=beforeRange,proto3" json:"before_range,omitempty"`
	Range            []*ChunkLocation       `protobuf:"bytes,5,rep,name=range,proto3" json:"range,omitempty"`
	AfterRange       []*ChunkLocation       `protobuf:"bytes,6,rep,name=after_range,json=afterRange,proto3" json:"after_range,omitempty"`
	StartOffsetRange uint64                 `protobuf:"varint,7,opt,name=start_offset_range,json=startOffsetRange,proto3" json:"start_offset_range,omitempty"`
	EndOffsetRange   uint64                 `protobuf:"varint,8,opt,name=end_offset_range,json=endOffsetRange,proto3" json:"end_offset_range,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RangeDeleteChunkRequest) Reset() {
	*x = RangeDeleteChunkRequest{}
	mi := &file_chunk_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeDeleteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeDeleteChunkRequest) ProtoMessage() {}

func (x *RangeDeleteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeDeleteChunkRequest.ProtoReflect.Descriptor instead.
func (*RangeDeleteChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{8}
}

func (x *RangeDeleteChunkRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RangeDeleteChunkRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RangeDeleteChunkRequest) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *RangeDeleteChunkRequest) GetBeforeRange() []*ChunkLocation {
	if x != nil {
		return x.BeforeRange
	}
	return nil
}

func (x *RangeDeleteChunkRequest) GetRange() []*ChunkLocation {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *RangeDeleteChunkRequest) GetAfterRange() []*ChunkLocation {
	if x != nil {
		return x.AfterRange
	}
	return nil
}

func (x *RangeDeleteChunkRequest) GetStartOffsetRange() uint64 {
	if x != nil {
		return x.StartOffsetRange
	}
	return 0
}

func (x *RangeDeleteChunkRequest) GetEndOffsetRange() uint64 {
	if x != nil {
		return x.EndOffsetRange
	}
	return 0
}

type RangeDeleteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeDeleteChunkResponse) Reset() {
	*x = RangeDeleteChunkResponse{}
	mi := &file_chunk_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeDeleteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeDeleteChunkResponse) ProtoMessage() {}

func (x *RangeDeleteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeDeleteChunkResponse.ProtoReflect.Descriptor instead.
func (*RangeDeleteChunkResponse) Descriptor() ([]byte, []int) {
	return file_chunk_proto_rawDescGZIP(), []int{9}
}

func (x *RangeDeleteChunkResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_chunk_proto protoreflect.FileDescriptor

const file_chunk_proto_rawDesc = "" +
	"\n" +
	"\vchunk.proto\x12\x03gfs\x1a\fcommon.proto\"t\n" +
	"\x11WriteChunkRequest\x123\n" +
	"\fchunk_handle\x18\x01 \x01(\v2\x10.gfs.ChunkHandleR\vchunkHandle\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"9\n" +
	"\x12WriteChunkResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\"w\n" +
	"\x10ReadChunkRequest\x123\n" +
	"\fchunk_handle\x18\x01 \x01(\v2\x10.gfs.ChunkHandleR\vchunkHandle\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\"L\n" +
	"\x11ReadChunkResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"I\n" +
	"\x12DeleteChunkRequest\x123\n" +
	"\fchunk_handle\x18\x01 \x01(\v2\x10.gfs.ChunkHandleR\vchunkHandle\":\n" +
	"\x13DeleteChunkResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\"\x8e\x01\n" +
	"\x10HeartbeatRequest\x12'\n" +
	"\x06server\x18\x01 \x01(\v2\x0f.gfs.ServerInfoR\x06server\x12(\n" +
	"\x06chunks\x18\x02 \x03(\v2\x10.gfs.ChunkHandleR\x06chunks\x12'\n" +
	"\x0favailable_space\x18\x03 \x01(\x04R\x0eavailableSpace\"8\n" +
	"\x11HeartbeatResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\"\xcb\x02\n" +
	"\x17RangeDeleteChunkRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\x125\n" +
	"\fbefore_range\x18\x04 \x03(\v2\x12.gfs.ChunkLocationR\vbeforeRange\x12(\n" +
	"\x05range\x18\x05 \x03(\v2\x12.gfs.ChunkLocationR\x05range\x123\n" +
	"\vafter_range\x18\x06 \x03(\v2\x12.gfs.ChunkLocationR\n" +
	"afterRange\x12,\n" +
	"\x12start_offset_range\x18\a \x01(\x04R\x10startOffsetRange\x12(\n" +
	"\x10end_offset_range\x18\b \x01(\x04R\x0eendOffsetRange\"?\n" +
	"\x18RangeDeleteChunkResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status2\xd8\x02\n" +
	"\fChunkService\x12=\n" +
	"\n" +
	"WriteChunk\x12\x16.gfs.WriteChunkRequest\x1a\x17.gfs.WriteChunkResponse\x12:\n" +
	"\tReadChunk\x12\x15.gfs.ReadChunkRequest\x1a\x16.gfs.ReadChunkResponse\x12@\n" +
	"\vDeleteChunk\x12\x17.gfs.DeleteChunkRequest\x1a\x18.gfs.DeleteChunkResponse\x12:\n" +
	"\tHeartbeat\x12\x15.gfs.HeartbeatRequest\x1a\x16.gfs.HeartbeatResponse\x12O\n" +
	"\x10RangeDeleteChunk\x12\x1c.gfs.RangeDeleteChunkRequest\x1a\x1d.gfs.RangeDeleteChunkResponseB*Z(github.com/Tharunqi/mini-gfs/internal/pbb\x06proto3"

var (
	file_chunk_proto_rawDescOnce sync.Once
	file_chunk_proto_rawDescData []byte
)

func file_chunk_proto_rawDescGZIP() []byte {
	file_chunk_proto_rawDescOnce.Do(func() {
		file_chunk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chunk_proto_rawDesc), len(file_chunk_proto_rawDesc)))
	})
	return file_chunk_proto_rawDescData
}

var file_chunk_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_chunk_proto_goTypes = []any{
	(*WriteChunkRequest)(nil),        // 0: gfs.WriteChunkRequest
	(*WriteChunkResponse)(nil),       // 1: gfs.WriteChunkResponse
	(*ReadChunkRequest)(nil),         // 2: gfs.ReadChunkRequest
	(*ReadChunkResponse)(nil),        // 3: gfs.ReadChunkResponse
	(*DeleteChunkRequest)(nil),       // 4: gfs.DeleteChunkRequest
	(*DeleteChunkResponse)(nil),      // 5: gfs.DeleteChunkResponse
	(*HeartbeatRequest)(nil),         // 6: gfs.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 7: gfs.HeartbeatResponse
	(*RangeDeleteChunkRequest)(nil),  // 8: gfs.RangeDeleteChunkRequest
	(*RangeDeleteChunkResponse)(nil), // 9: gfs.RangeDeleteChunkResponse
	(*ChunkHandle)(nil),              // 10: gfs.ChunkHandle
	(*Status)(nil),                   // 11: gfs.Status
	(*ServerInfo)(nil),               // 12: gfs.ServerInfo
	(*ChunkLocation)(nil),            // 13: gfs.ChunkLocation
}
var file_chunk_proto_depIdxs = []int32{
	10, // 0: gfs.WriteChunkRequest.chunk_handle:type_name -> gfs.ChunkHandle
	11, // 1: gfs.WriteChunkResponse.status:type_name -> gfs.Status
	10, // 2: gfs.ReadChunkRequest.chunk_handle:type_name -> gfs.ChunkHandle
	11, // 3: gfs.ReadChunkResponse.status:type_name -> gfs.Status
	10, // 4: gfs.DeleteChunkRequest.chunk_handle:type_name -> gfs.ChunkHandle
	11, // 5: gfs.DeleteChunkResponse.status:type_name -> gfs.Status
	12, // 6: gfs.HeartbeatRequest.server:type_name -> gfs.ServerInfo
	10, // 7: gfs.HeartbeatRequest.chunks:type_name -> gfs.ChunkHandle
	11, // 8: gfs.HeartbeatResponse.status:type_name -> gfs.Status
	13, // 9: gfs.RangeDeleteChunkRequest.before_range:type_name -> gfs.ChunkLocation
	13, // 10: gfs.RangeDeleteChunkRequest.range:type_name -> gfs.ChunkLocation
	13, // 11: gfs.RangeDeleteChunkRequest.after_range:type_name -> gfs.ChunkLocation
	11, // 12: gfs.RangeDeleteChunkResponse.status:type_name -> gfs.Status
	0,  // 13: gfs.ChunkService.WriteChunk:input_type -> gfs.WriteChunkRequest
	2,  // 14: gfs.ChunkService.ReadChunk:input_type -> gfs.ReadChunkRequest
	4,  // 15: gfs.ChunkService.DeleteChunk:input_type -> gfs.DeleteChunkRequest
	6,  // 16: gfs.ChunkService.Heartbeat:input_type -> gfs.HeartbeatRequest
	8,  // 17: gfs.ChunkService.RangeDeleteChunk:input_type -> gfs.RangeDeleteChunkRequest
	1,  // 18: gfs.ChunkService.WriteChunk:output_type -> gfs.WriteChunkResponse
	3,  // 19: gfs.ChunkService.ReadChunk:output_type -> gfs.ReadChunkResponse
	5,  // 20: gfs.ChunkService.DeleteChunk:output_type -> gfs.DeleteChunkResponse
	7,  // 21: gfs.ChunkService.Heartbeat:output_type -> gfs.HeartbeatResponse
	9,  // 22: gfs.ChunkService.RangeDeleteChunk:output_type -> gfs.RangeDeleteChunkResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_chunk_proto_init() }
func file_chunk_proto_init() {
	if File_chunk_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chunk_proto_rawDesc), len(file_chunk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chunk_proto_goTypes,
		DependencyIndexes: file_chunk_proto_depIdxs,
		MessageInfos:      file_chunk_proto_msgTypes,
	}.Build()
	File_chunk_proto = out.File
	file_chunk_proto_goTypes = nil
	file_chunk_proto_depIdxs = nil
}
