// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: master.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreateFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileResponse) Reset() {
	*x = CreateFileResponse{}
	mi := &file_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResponse) ProtoMessage() {}

func (x *CreateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResponse.ProtoReflect.Descriptor instead.
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFileResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type OpenFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFileRequest) Reset() {
	*x = OpenFileRequest{}
	mi := &file_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFileRequest) ProtoMessage() {}

func (x *OpenFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFileRequest.ProtoReflect.Descriptor instead.
func (*OpenFileRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{2}
}

func (x *OpenFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type OpenFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Chunks        []*ChunkHandle         `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFileResponse) Reset() {
	*x = OpenFileResponse{}
	mi := &file_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFileResponse) ProtoMessage() {}

func (x *OpenFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFileResponse.ProtoReflect.Descriptor instead.
func (*OpenFileResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{3}
}

func (x *OpenFileResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *OpenFileResponse) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *OpenFileResponse) GetChunks() []*ChunkHandle {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFileResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetChunkLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHandle   *ChunkHandle           `protobuf:"bytes,1,opt,name=chunk_handle,json=chunkHandle,proto3" json:"chunk_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkLocationsRequest) Reset() {
	*x = GetChunkLocationsRequest{}
	mi := &file_master_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkLocationsRequest) ProtoMessage() {}

func (x *GetChunkLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkLocationsRequest.ProtoReflect.Descriptor instead.
func (*GetChunkLocationsRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{6}
}

func (x *GetChunkLocationsRequest) GetChunkHandle() *ChunkHandle {
	if x != nil {
		return x.ChunkHandle
	}
	return nil
}

type GetChunkLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Location      *ChunkLocation         `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkLocationsResponse) Reset() {
	*x = GetChunkLocationsResponse{}
	mi := &file_master_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkLocationsResponse) ProtoMessage() {}

func (x *GetChunkLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkLocationsResponse.ProtoReflect.Descriptor instead.
func (*GetChunkLocationsResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{7}
}

func (x *GetChunkLocationsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetChunkLocationsResponse) GetLocation() *ChunkLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type AllocateChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunkRequest) Reset() {
	*x = AllocateChunkRequest{}
	mi := &file_master_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunkRequest) ProtoMessage() {}

func (x *AllocateChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunkRequest.ProtoReflect.Descriptor instead.
func (*AllocateChunkRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{8}
}

func (x *AllocateChunkRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type AllocateChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Location      *ChunkLocation         `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunkResponse) Reset() {
	*x = AllocateChunkResponse{}
	mi := &file_master_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunkResponse) ProtoMessage() {}

func (x *AllocateChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunkResponse.ProtoReflect.Descriptor instead.
func (*AllocateChunkResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{9}
}

func (x *AllocateChunkResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AllocateChunkResponse) GetLocation() *ChunkLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

var File_master_proto protoreflect.FileDescriptor

const file_master_proto_rawDesc = "" +
	"\n" +
	"\fmaster.proto\x12\x03gfs\x1a\fcommon.proto\"'\n" +
	"\x11CreateFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"9\n" +
	"\x12CreateFileResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\"%\n" +
	"\x0fOpenFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x80\x01\n" +
	"\x10OpenFileResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\x12(\n" +
	"\x06chunks\x18\x03 \x03(\v2\x10.gfs.ChunkHandleR\x06chunks\"'\n" +
	"\x11DeleteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"9\n" +
	"\x12DeleteFileResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\"O\n" +
	"\x18GetChunkLocationsRequest\x123\n" +
	"\fchunk_handle\x18\x01 \x01(\v2\x10.gfs.ChunkHandleR\vchunkHandle\"p\n" +
	"\x19GetChunkLocationsResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\x12.\n" +
	"\blocation\x18\x02 \x01(\v2\x12.gfs.ChunkLocationR\blocation\"*\n" +
	"\x14AllocateChunkRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"l\n" +
	"\x15AllocateChunkResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\x12.\n" +
	"\blocation\x18\x02 \x01(\v2\x12.gfs.ChunkLocationR\blocation2\xe2\x02\n" +
	"\rMasterService\x12=\n" +
	"\n" +
	"CreateFile\x12\x16.gfs.CreateFileRequest\x1a\x17.gfs.CreateFileResponse\x127\n" +
	"\bOpenFile\x12\x14.gfs.OpenFileRequest\x1a\x15.gfs.OpenFileResponse\x12=\n" +
	"\n" +
	"DeleteFile\x12\x16.gfs.DeleteFileRequest\x1a\x17.gfs.DeleteFileResponse\x12R\n" +
	"\x11GetChunkLocations\x12\x1d.gfs.GetChunkLocationsRequest\x1a\x1e.gfs.GetChunkLocationsResponse\x12F\n" +
	"\rAllocateChunk\x12\x19.gfs.AllocateChunkRequest\x1a\x1a.gfs.AllocateChunkResponseB*Z(github.com/Tharunqi/mini-gfs/internal/pbb\x06proto3"

var (
	file_master_proto_rawDescOnce sync.Once
	file_master_proto_rawDescData []byte
)

func file_master_proto_rawDescGZIP() []byte {
	file_master_proto_rawDescOnce.Do(func() {
		file_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_master_proto_rawDesc), len(file_master_proto_rawDesc)))
	})
	return file_master_proto_rawDescData
}

var file_master_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_master_proto_goTypes = []any{
	(*CreateFileRequest)(nil),         // 0: gfs.CreateFileRequest
	(*CreateFileResponse)(nil),        // 1: gfs.CreateFileResponse
	(*OpenFileRequest)(nil),           // 2: gfs.OpenFileRequest
	(*OpenFileResponse)(nil),          // 3: gfs.OpenFileResponse
	(*DeleteFileRequest)(nil),         // 4: gfs.DeleteFileRequest
	(*DeleteFileResponse)(nil),        // 5: gfs.DeleteFileResponse
	(*GetChunkLocationsRequest)(nil),  // 6: gfs.GetChunkLocationsRequest
	(*GetChunkLocationsResponse)(nil), // 7: gfs.GetChunkLocationsResponse
	(*AllocateChunkRequest)(nil),      // 8: gfs.AllocateChunkRequest
	(*AllocateChunkResponse)(nil),     // 9: gfs.AllocateChunkResponse
	(*Status)(nil),                    // 10: gfs.Status
	(*ChunkHandle)(nil),               // 11: gfs.ChunkHandle
	(*ChunkLocation)(nil),             // 12: gfs.ChunkLocation
}
var file_master_proto_depIdxs = []int32{
	10, // 0: gfs.CreateFileResponse.status:type_name -> gfs.Status
	10, // 1: gfs.OpenFileResponse.status:type_name -> gfs.Status
	11, // 2: gfs.OpenFileResponse.chunks:type_name -> gfs.ChunkHandle
	10, // 3: gfs.DeleteFileResponse.status:type_name -> gfs.Status
	11, // 4: gfs.GetChunkLocationsRequest.chunk_handle:type_name -> gfs.ChunkHandle
	10, // 5: gfs.GetChunkLocationsResponse.status:type_name -> gfs.Status
	12, // 6: gfs.GetChunkLocationsResponse.location:type_name -> gfs.ChunkLocation
	10, // 7: gfs.AllocateChunkResponse.status:type_name -> gfs.Status
	12, // 8: gfs.AllocateChunkResponse.location:type_name -> gfs.ChunkLocation
	0,  // 9: gfs.MasterService.CreateFile:input_type -> gfs.CreateFileRequest
	2,  // 10: gfs.MasterService.OpenFile:input_type -> gfs.OpenFileRequest
	4,  // 11: gfs.MasterService.DeleteFile:input_type -> gfs.DeleteFileRequest
	6,  // 12: gfs.MasterService.GetChunkLocations:input_type -> gfs.GetChunkLocationsRequest
	8,  // 13: gfs.MasterService.AllocateChunk:input_type -> gfs.AllocateChunkRequest
	1,  // 14: gfs.MasterService.CreateFile:output_type -> gfs.CreateFileResponse
	3,  // 15: gfs.MasterService.OpenFile:output_type -> gfs.OpenFileResponse
	5,  // 16: gfs.MasterService.DeleteFile:output_type -> gfs.DeleteFileResponse
	7,  // 17: gfs.MasterService.GetChunkLocations:output_type -> gfs.GetChunkLocationsResponse
	9,  // 18: gfs.MasterService.AllocateChunk:output_type -> gfs.AllocateChunkResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_master_proto_init() }
func file_master_proto_init() {
	if File_master_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_master_proto_rawDesc), len(file_master_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_master_proto_goTypes,
		DependencyIndexes: file_master_proto_depIdxs,
		MessageInfos:      file_master_proto_msgTypes,
	}.Build()
	File_master_proto = out.File
	file_master_proto_goTypes = nil
	file_master_proto_depIdxs = nil
}
