// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: master.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreateFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileResponse) Reset() {
	*x = CreateFileResponse{}
	mi := &file_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResponse) ProtoMessage() {}

func (x *CreateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResponse.ProtoReflect.Descriptor instead.
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFileResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type OpenFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFileRequest) Reset() {
	*x = OpenFileRequest{}
	mi := &file_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFileRequest) ProtoMessage() {}

func (x *OpenFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFileRequest.ProtoReflect.Descriptor instead.
func (*OpenFileRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{2}
}

func (x *OpenFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type OpenFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Chunks        []*ChunkHandle         `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFileResponse) Reset() {
	*x = OpenFileResponse{}
	mi := &file_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFileResponse) ProtoMessage() {}

func (x *OpenFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFileResponse.ProtoReflect.Descriptor instead.
func (*OpenFileResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{3}
}

func (x *OpenFileResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *OpenFileResponse) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *OpenFileResponse) GetChunks() []*ChunkHandle {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFileResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetChunkLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHandle   *ChunkHandle           `protobuf:"bytes,1,opt,name=chunk_handle,json=chunkHandle,proto3" json:"chunk_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkLocationsRequest) Reset() {
	*x = GetChunkLocationsRequest{}
	mi := &file_master_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkLocationsRequest) ProtoMessage() {}

func (x *GetChunkLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkLocationsRequest.ProtoReflect.Descriptor instead.
func (*GetChunkLocationsRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{6}
}

func (x *GetChunkLocationsRequest) GetChunkHandle() *ChunkHandle {
	if x != nil {
		return x.ChunkHandle
	}
	return nil
}

type GetChunkLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Location      *ChunkLocation         `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkLocationsResponse) Reset() {
	*x = GetChunkLocationsResponse{}
	mi := &file_master_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkLocationsResponse) ProtoMessage() {}

func (x *GetChunkLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkLocationsResponse.ProtoReflect.Descriptor instead.
func (*GetChunkLocationsResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{7}
}

func (x *GetChunkLocationsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetChunkLocationsResponse) GetLocation() *ChunkLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type AllocateChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunkRequest) Reset() {
	*x = AllocateChunkRequest{}
	mi := &file_master_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunkRequest) ProtoMessage() {}

func (x *AllocateChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunkRequest.ProtoReflect.Descriptor instead.
func (*AllocateChunkRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{8}
}

func (x *AllocateChunkRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type AllocateChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Location      *ChunkLocation         `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunkResponse) Reset() {
	*x = AllocateChunkResponse{}
	mi := &file_master_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunkResponse) ProtoMessage() {}

func (x *AllocateChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunkResponse.ProtoReflect.Descriptor instead.
func (*AllocateChunkResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{9}
}

func (x *AllocateChunkResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AllocateChunkResponse) GetLocation() *ChunkLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type UpdateChunkMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *ChunkHandle           `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	BytesWritten  uint64                 `protobuf:"varint,2,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChunkMetadataRequest) Reset() {
	*x = UpdateChunkMetadataRequest{}
	mi := &file_master_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChunkMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChunkMetadataRequest) ProtoMessage() {}

func (x *UpdateChunkMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChunkMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateChunkMetadataRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateChunkMetadataRequest) GetHandle() *ChunkHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *UpdateChunkMetadataRequest) GetBytesWritten() uint64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *UpdateChunkMetadataRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UpdateChunkMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChunkMetadataResponse) Reset() {
	*x = UpdateChunkMetadataResponse{}
	mi := &file_master_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChunkMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChunkMetadataResponse) ProtoMessage() {}

func (x *UpdateChunkMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChunkMetadataResponse.ProtoReflect.Descriptor instead.
func (*UpdateChunkMetadataResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateChunkMetadataResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_master_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{12}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteFileRequest) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Locations     []*ChunkLocation       `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_master_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{13}
}

func (x *WriteFileResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *WriteFileResponse) GetLocations() []*ChunkLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

type AppendFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Length        uint64                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendFileRequest) Reset() {
	*x = AppendFileRequest{}
	mi := &file_master_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendFileRequest) ProtoMessage() {}

func (x *AppendFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendFileRequest.ProtoReflect.Descriptor instead.
func (*AppendFileRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{14}
}

func (x *AppendFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AppendFileRequest) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type AppendFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Locations     []*ChunkLocation       `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendFileResponse) Reset() {
	*x = AppendFileResponse{}
	mi := &file_master_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendFileResponse) ProtoMessage() {}

func (x *AppendFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendFileResponse.ProtoReflect.Descriptor instead.
func (*AppendFileResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{15}
}

func (x *AppendFileResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AppendFileResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AppendFileResponse) GetLocations() []*ChunkLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

type RangeDeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeDeleteFileRequest) Reset() {
	*x = RangeDeleteFileRequest{}
	mi := &file_master_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeDeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeDeleteFileRequest) ProtoMessage() {}

func (x *RangeDeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeDeleteFileRequest.ProtoReflect.Descriptor instead.
func (*RangeDeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{16}
}

func (x *RangeDeleteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RangeDeleteFileRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RangeDeleteFileRequest) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type RangeDeleteFileResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	BeforeRange      []*ChunkLocation       `protobuf:"bytes,2,rep,name=before_range,json=beforeRange,proto3" json:"before_range,omitempty"`
	Range            []*ChunkLocation       `protobuf:"bytes,3,rep,name=range,proto3" json:"range,omitempty"`
	AfterRange       []*ChunkLocation       `protobuf:"bytes,4,rep,name=after_range,json=afterRange,proto3" json:"after_range,omitempty"`
	StartOffsetRange uint64                 `protobuf:"varint,5,opt,name=start_offset_range,json=startOffsetRange,proto3" json:"start_offset_range,omitempty"`
	EndOffsetRange   uint64                 `protobuf:"varint,6,opt,name=end_offset_range,json=endOffsetRange,proto3" json:"end_offset_range,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RangeDeleteFileResponse) Reset() {
	*x = RangeDeleteFileResponse{}
	mi := &file_master_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeDeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeDeleteFileResponse) ProtoMessage() {}

func (x *RangeDeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeDeleteFileResponse.ProtoReflect.Descriptor instead.
func (*RangeDeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{17}
}

func (x *RangeDeleteFileResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RangeDeleteFileResponse) GetBeforeRange() []*ChunkLocation {
	if x != nil {
		return x.BeforeRange
	}
	return nil
}

func (x *RangeDeleteFileResponse) GetRange() []*ChunkLocation {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *RangeDeleteFileResponse) GetAfterRange() []*ChunkLocation {
	if x != nil {
		return x.AfterRange
	}
	return nil
}

func (x *RangeDeleteFileResponse) GetStartOffsetRange() uint64 {
	if x != nil {
		return x.StartOffsetRange
	}
	return 0
}

func (x *RangeDeleteFileResponse) GetEndOffsetRange() uint64 {
	if x != nil {
		return x.EndOffsetRange
	}
	return 0
}

type UpdateMasterMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	NewSize       uint64                 `protobuf:"varint,2,opt,name=new_size,json=newSize,proto3" json:"new_size,omitempty"`
	Chunks        []*ChunkHandle         `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMasterMetadataRequest) Reset() {
	*x = UpdateMasterMetadataRequest{}
	mi := &file_master_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMasterMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMasterMetadataRequest) ProtoMessage() {}

func (x *UpdateMasterMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMasterMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateMasterMetadataRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateMasterMetadataRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpdateMasterMetadataRequest) GetNewSize() uint64 {
	if x != nil {
		return x.NewSize
	}
	return 0
}

func (x *UpdateMasterMetadataRequest) GetChunks() []*ChunkHandle {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type UpdateMasterMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMasterMetadataResponse) Reset() {
	*x = UpdateMasterMetadataResponse{}
	mi := &file_master_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMasterMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMasterMetadataResponse) ProtoMessage() {}

func (x *UpdateMasterMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMasterMetadataResponse.ProtoReflect.Descriptor instead.
func (*UpdateMasterMetadataResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateMasterMetadataResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_master_proto protoreflect.FileDescriptor

const file_master_proto_rawDesc = "" +
	"\n" +
	"\fmaster.proto\x12\x03gfs\x1a\fcommon.proto\"'\n" +
	"\x11CreateFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"9\n" +
	"\x12CreateFileResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\"%\n" +
	"\x0fOpenFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x80\x01\n" +
	"\x10OpenFileResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\x12(\n" +
	"\x06chunks\x18\x03 \x03(\v2\x10.gfs.ChunkHandleR\x06chunks\"'\n" +
	"\x11DeleteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"9\n" +
	"\x12DeleteFileResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\"O\n" +
	"\x18GetChunkLocationsRequest\x123\n" +
	"\fchunk_handle\x18\x01 \x01(\v2\x10.gfs.ChunkHandleR\vchunkHandle\"p\n" +
	"\x19GetChunkLocationsResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\x12.\n" +
	"\blocation\x18\x02 \x01(\v2\x12.gfs.ChunkLocationR\blocation\"*\n" +
	"\x14AllocateChunkRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"l\n" +
	"\x15AllocateChunkResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\x12.\n" +
	"\blocation\x18\x02 \x01(\v2\x12.gfs.ChunkLocationR\blocation\"\x83\x01\n" +
	"\x1aUpdateChunkMetadataRequest\x12(\n" +
	"\x06handle\x18\x01 \x01(\v2\x10.gfs.ChunkHandleR\x06handle\x12#\n" +
	"\rbytes_written\x18\x02 \x01(\x04R\fbytesWritten\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"B\n" +
	"\x1bUpdateChunkMetadataResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\"V\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\"j\n" +
	"\x11WriteFileResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\x120\n" +
	"\tlocations\x18\x02 \x03(\v2\x12.gfs.ChunkLocationR\tlocations\"?\n" +
	"\x11AppendFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\"\x83\x01\n" +
	"\x12AppendFileResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x120\n" +
	"\tlocations\x18\x03 \x03(\v2\x12.gfs.ChunkLocationR\tlocations\"\\\n" +
	"\x16RangeDeleteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\"\xac\x02\n" +
	"\x17RangeDeleteFileResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status\x125\n" +
	"\fbefore_range\x18\x02 \x03(\v2\x12.gfs.ChunkLocationR\vbeforeRange\x12(\n" +
	"\x05range\x18\x03 \x03(\v2\x12.gfs.ChunkLocationR\x05range\x123\n" +
	"\vafter_range\x18\x04 \x03(\v2\x12.gfs.ChunkLocationR\n" +
	"afterRange\x12,\n" +
	"\x12start_offset_range\x18\x05 \x01(\x04R\x10startOffsetRange\x12(\n" +
	"\x10end_offset_range\x18\x06 \x01(\x04R\x0eendOffsetRange\"v\n" +
	"\x1bUpdateMasterMetadataRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bnew_size\x18\x02 \x01(\x04R\anewSize\x12(\n" +
	"\x06chunks\x18\x03 \x03(\v2\x10.gfs.ChunkHandleR\x06chunks\"C\n" +
	"\x1cUpdateMasterMetadataResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\v2\v.gfs.StatusR\x06status2\xe2\x05\n" +
	"\rMasterService\x12=\n" +
	"\n" +
	"CreateFile\x12\x16.gfs.CreateFileRequest\x1a\x17.gfs.CreateFileResponse\x127\n" +
	"\bOpenFile\x12\x14.gfs.OpenFileRequest\x1a\x15.gfs.OpenFileResponse\x12=\n" +
	"\n" +
	"DeleteFile\x12\x16.gfs.DeleteFileRequest\x1a\x17.gfs.DeleteFileResponse\x12R\n" +
	"\x11GetChunkLocations\x12\x1d.gfs.GetChunkLocationsRequest\x1a\x1e.gfs.GetChunkLocationsResponse\x12F\n" +
	"\rAllocateChunk\x12\x19.gfs.AllocateChunkRequest\x1a\x1a.gfs.AllocateChunkResponse\x12X\n" +
	"\x13UpdateChunkMetadata\x12\x1f.gfs.UpdateChunkMetadataRequest\x1a .gfs.UpdateChunkMetadataResponse\x12:\n" +
	"\tWriteFile\x12\x15.gfs.WriteFileRequest\x1a\x16.gfs.WriteFileResponse\x12=\n" +
	"\n" +
	"AppendFile\x12\x16.gfs.AppendFileRequest\x1a\x17.gfs.AppendFileResponse\x12L\n" +
	"\x0fRangeDeleteFile\x12\x1b.gfs.RangeDeleteFileRequest\x1a\x1c.gfs.RangeDeleteFileResponse\x12[\n" +
	"\x14UpdateMasterMetadata\x12 .gfs.UpdateMasterMetadataRequest\x1a!.gfs.UpdateMasterMetadataResponseB*Z(github.com/Tharunqi/mini-gfs/internal/pbb\x06proto3"

var (
	file_master_proto_rawDescOnce sync.Once
	file_master_proto_rawDescData []byte
)

func file_master_proto_rawDescGZIP() []byte {
	file_master_proto_rawDescOnce.Do(func() {
		file_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_master_proto_rawDesc), len(file_master_proto_rawDesc)))
	})
	return file_master_proto_rawDescData
}

var file_master_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_master_proto_goTypes = []any{
	(*CreateFileRequest)(nil),            // 0: gfs.CreateFileRequest
	(*CreateFileResponse)(nil),           // 1: gfs.CreateFileResponse
	(*OpenFileRequest)(nil),              // 2: gfs.OpenFileRequest
	(*OpenFileResponse)(nil),             // 3: gfs.OpenFileResponse
	(*DeleteFileRequest)(nil),            // 4: gfs.DeleteFileRequest
	(*DeleteFileResponse)(nil),           // 5: gfs.DeleteFileResponse
	(*GetChunkLocationsRequest)(nil),     // 6: gfs.GetChunkLocationsRequest
	(*GetChunkLocationsResponse)(nil),    // 7: gfs.GetChunkLocationsResponse
	(*AllocateChunkRequest)(nil),         // 8: gfs.AllocateChunkRequest
	(*AllocateChunkResponse)(nil),        // 9: gfs.AllocateChunkResponse
	(*UpdateChunkMetadataRequest)(nil),   // 10: gfs.UpdateChunkMetadataRequest
	(*UpdateChunkMetadataResponse)(nil),  // 11: gfs.UpdateChunkMetadataResponse
	(*WriteFileRequest)(nil),             // 12: gfs.WriteFileRequest
	(*WriteFileResponse)(nil),            // 13: gfs.WriteFileResponse
	(*AppendFileRequest)(nil),            // 14: gfs.AppendFileRequest
	(*AppendFileResponse)(nil),           // 15: gfs.AppendFileResponse
	(*RangeDeleteFileRequest)(nil),       // 16: gfs.RangeDeleteFileRequest
	(*RangeDeleteFileResponse)(nil),      // 17: gfs.RangeDeleteFileResponse
	(*UpdateMasterMetadataRequest)(nil),  // 18: gfs.UpdateMasterMetadataRequest
	(*UpdateMasterMetadataResponse)(nil), // 19: gfs.UpdateMasterMetadataResponse
	(*Status)(nil),                       // 20: gfs.Status
	(*ChunkHandle)(nil),                  // 21: gfs.ChunkHandle
	(*ChunkLocation)(nil),                // 22: gfs.ChunkLocation
}
var file_master_proto_depIdxs = []int32{
	20, // 0: gfs.CreateFileResponse.status:type_name -> gfs.Status
	20, // 1: gfs.OpenFileResponse.status:type_name -> gfs.Status
	21, // 2: gfs.OpenFileResponse.chunks:type_name -> gfs.ChunkHandle
	20, // 3: gfs.DeleteFileResponse.status:type_name -> gfs.Status
	21, // 4: gfs.GetChunkLocationsRequest.chunk_handle:type_name -> gfs.ChunkHandle
	20, // 5: gfs.GetChunkLocationsResponse.status:type_name -> gfs.Status
	22, // 6: gfs.GetChunkLocationsResponse.location:type_name -> gfs.ChunkLocation
	20, // 7: gfs.AllocateChunkResponse.status:type_name -> gfs.Status
	22, // 8: gfs.AllocateChunkResponse.location:type_name -> gfs.ChunkLocation
	21, // 9: gfs.UpdateChunkMetadataRequest.handle:type_name -> gfs.ChunkHandle
	20, // 10: gfs.UpdateChunkMetadataResponse.status:type_name -> gfs.Status
	20, // 11: gfs.WriteFileResponse.status:type_name -> gfs.Status
	22, // 12: gfs.WriteFileResponse.locations:type_name -> gfs.ChunkLocation
	20, // 13: gfs.AppendFileResponse.status:type_name -> gfs.Status
	22, // 14: gfs.AppendFileResponse.locations:type_name -> gfs.ChunkLocation
	20, // 15: gfs.RangeDeleteFileResponse.status:type_name -> gfs.Status
	22, // 16: gfs.RangeDeleteFileResponse.before_range:type_name -> gfs.ChunkLocation
	22, // 17: gfs.RangeDeleteFileResponse.range:type_name -> gfs.ChunkLocation
	22, // 18: gfs.RangeDeleteFileResponse.after_range:type_name -> gfs.ChunkLocation
	21, // 19: gfs.UpdateMasterMetadataRequest.chunks:type_name -> gfs.ChunkHandle
	20, // 20: gfs.UpdateMasterMetadataResponse.status:type_name -> gfs.Status
	0,  // 21: gfs.MasterService.CreateFile:input_type -> gfs.CreateFileRequest
	2,  // 22: gfs.MasterService.OpenFile:input_type -> gfs.OpenFileRequest
	4,  // 23: gfs.MasterService.DeleteFile:input_type -> gfs.DeleteFileRequest
	6,  // 24: gfs.MasterService.GetChunkLocations:input_type -> gfs.GetChunkLocationsRequest
	8,  // 25: gfs.MasterService.AllocateChunk:input_type -> gfs.AllocateChunkRequest
	10, // 26: gfs.MasterService.UpdateChunkMetadata:input_type -> gfs.UpdateChunkMetadataRequest
	12, // 27: gfs.MasterService.WriteFile:input_type -> gfs.WriteFileRequest
	14, // 28: gfs.MasterService.AppendFile:input_type -> gfs.AppendFileRequest
	16, // 29: gfs.MasterService.RangeDeleteFile:input_type -> gfs.RangeDeleteFileRequest
	18, // 30: gfs.MasterService.UpdateMasterMetadata:input_type -> gfs.UpdateMasterMetadataRequest
	1,  // 31: gfs.MasterService.CreateFile:output_type -> gfs.CreateFileResponse
	3,  // 32: gfs.MasterService.OpenFile:output_type -> gfs.OpenFileResponse
	5,  // 33: gfs.MasterService.DeleteFile:output_type -> gfs.DeleteFileResponse
	7,  // 34: gfs.MasterService.GetChunkLocations:output_type -> gfs.GetChunkLocationsResponse
	9,  // 35: gfs.MasterService.AllocateChunk:output_type -> gfs.AllocateChunkResponse
	11, // 36: gfs.MasterService.UpdateChunkMetadata:output_type -> gfs.UpdateChunkMetadataResponse
	13, // 37: gfs.MasterService.WriteFile:output_type -> gfs.WriteFileResponse
	15, // 38: gfs.MasterService.AppendFile:output_type -> gfs.AppendFileResponse
	17, // 39: gfs.MasterService.RangeDeleteFile:output_type -> gfs.RangeDeleteFileResponse
	19, // 40: gfs.MasterService.UpdateMasterMetadata:output_type -> gfs.UpdateMasterMetadataResponse
	31, // [31:41] is the sub-list for method output_type
	21, // [21:31] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_master_proto_init() }
func file_master_proto_init() {
	if File_master_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_master_proto_rawDesc), len(file_master_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_master_proto_goTypes,
		DependencyIndexes: file_master_proto_depIdxs,
		MessageInfos:      file_master_proto_msgTypes,
	}.Build()
	File_master_proto = out.File
	file_master_proto_goTypes = nil
	file_master_proto_depIdxs = nil
}
