syntax = "proto3";

package gfs;

option go_package = "github.com/Tharunqi/mini-gfs/internal/pb";


message ChunkHandle{
    uint64 id = 1;
    string path = 2;
}

message ServerInfo{
    string id = 1;
    string host = 2;
    uint32 port = 3;
}

message ChunkLocation{
    ChunkHandle handle = 1;
    ServerInfo primary = 2;
    repeated ServerInfo replicas = 3;
}

message LeaseInfo{
    ServerInfo primary = 1;
    int64 expiry_unix = 2;
}

message Status{
    bool success = 1;
    string message = 2;
}