syntax = "proto3";

package gfs;

option go_package = "github.com/Tharunqi/mini-gfs/internal/pb";
import "common.proto";


message CreateFileRequest {
    string path = 1;
}

message CreateFileResponse {
    Status status = 1;
}

message OpenFileRequest {
    string path = 1;
}

message OpenFileResponse {
    Status status = 1;
    uint64 size_bytes = 2;
    repeated ChunkHandle chunks = 3;
}

message DeleteFileRequest {
    string path = 1;
}

message DeleteFileResponse {
    Status status = 1;
}

message GetChunkLocationsRequest {
    ChunkHandle chunk_handle = 1;
}

message GetChunkLocationsResponse {
    Status status = 1;
    ChunkLocation location = 2;
}

message AllocateChunkRequest {
    string path = 1;
    uint64 index = 2;
}

message AllocateChunkResponse {
    Status status = 1;
    ChunkLocation location = 2;
}

message WriteFileRequest{
    string path = 1;
    uint64 offset = 2;
    uint64 length = 3;
}

message WriteFileResponse{
    Status status = 1;
    repeated ChunkLocation locations = 2;
}

message AppendFileRequest{
    string path = 1;
    uint64 length = 2;
}

message AppendFileResponse{
    Status status = 1;
    uint64 offset = 2;
    repeated ChunkLocation locations = 3;
}

message RangeDeleteFileRequest{
    string path = 1;
    uint64 offset = 2;
    uint64 length = 3;
}

message RangeDeleteFileResponse{
    Status status = 1;
    repeated ChunkLocation before_range= 2;
    repeated ChunkLocation range = 3;
    repeated ChunkLocation after_range = 4;
    uint64 start_offset_range = 5;
    uint64 end_offset_range = 6;
}

message UpdateMasterMetadataRequest {
    string path = 1;
    uint64 size = 2;
    ChunkHandle chunk = 3;
    uint64 delete = 4;
}

message UpdateMasterMetadataResponse {
    Status status = 1;
}

message TruncateFileRequest{
    string path = 1;
    uint64 size = 2;
}

message TruncateFileResponse{
    Status status = 1;
    repeated ChunkLocation delete_chunks = 2;
    ChunkLocation truncate_chunk = 3;
    uint64 truncate_chunk_size = 4;
}

message InsertFileRequest{
    string path = 1;
    uint64 length = 2;
    uint64 offset = 3;
}

message InsertFileResponse{
    Status status = 1;
    ChunkLocation start_chunk = 2;
    uint64 start_offset = 3;
}

message RegisterChunkServerRequest {
    ServerInfo server = 1;
}

message RegisterChunkServerResponse {
    Status status = 1;
}

rpc DeleteChunkMetadata(
    DeleteChunkMetadataRequest
) returns (
    DeleteChunkMetadataResponse
);

service MasterService {
    rpc CreateFile(CreateFileRequest) returns (CreateFileResponse);

    rpc OpenFile(OpenFileRequest) returns (OpenFileResponse);

    rpc DeleteFile(DeleteFileRequest) returns (DeleteFileResponse);

    rpc GetChunkLocations(GetChunkLocationsRequest) returns (GetChunkLocationsResponse);

    rpc AllocateChunk(AllocateChunkRequest) returns (AllocateChunkResponse);

    rpc WriteFile(WriteFileRequest) returns (WriteFileResponse);

    rpc AppendFile(AppendFileRequest) returns (AppendFileResponse);

    rpc RangeDeleteFile(RangeDeleteFileRequest) returns (RangeDeleteFileResponse);

    rpc UpdateMasterMetadata(UpdateMasterMetadataRequest) returns (UpdateMasterMetadataResponse);

    rpc TruncateFile(TruncateFileRequest) returns (TruncateFileResponse);

    rpc InsertFile(InsertFileRequest) returns (InsertFileResponse);

    rpc RegisterChunkServer(RegisterChunkServerRequest) returns (RegisterChunkServerResponse);
}